### ISSUE TITLE
Vertical padding

### ISSUE THREAD

**Issue by jaimeiniesta** [abdelaz3r/simple_charts#30]
Hi, thanks for sharing this awesome library!

Is there a way to use only vertical padding? 

When using smoothing (even the default 0.15), the line can be cropped at the top and bottom borders:

![Captura de pantalla 2024-02-26 a las 14 46 03](https://github.com/abdelaz3r/sparkline_svg/assets/2629/18191c32-84ec-4e8e-9626-a68ae39004c8)

This can be fixed by setting padding, but then I also get horizontal padding, it would be great to have only padding at the top and bottom.

**Comment by abdelaz3r** [comment]
Hi,

Thanks for the comment ;)

It's funny because I actually addressed that just a few hours ago. It's still a work in progress but here is the pr: https://github.com/abdelaz3r/sparkline_svg/pull/29.

These updates are expected to be included in the upcoming v0.3 version.

**Comment by jaimeiniesta** [comment]
Awesome, thanks! I can confirm that the PR fixes that, here's the above charts with some vertical padding:

![Captura de pantalla 2024-02-26 a las 17 08 35](https://github.com/abdelaz3r/sparkline_svg/assets/2629/0e6a4321-e766-421a-a6b1-d56e278c5b37)

**Comment by abdelaz3r** [comment]
v0.3.0 has been released!

Please note that I made slight changes to the API compared to what you saw in the pull request.

``` elixir
# Both example are for padding top and bottom at 5, and left and right at 0.
# First version:
Sparkline_svg.new(data, padding: {5, 0})

# Current version:
Sparkline_svg.new(data, padding: [top: 5, left: 0, bottom: 5, right: 0])
```

**Comment by jaimeiniesta** [comment]
Thanks! Just upgraded and everything looks smooth. I like the new syntax, much clearer 👍
