### ISSUE TITLE
Crash when there are less than 2 values

### ISSUE THREAD

**Issue by jaimeiniesta** [abdelaz3r/simple_charts#31]
If the list of values has less than 2, we get this crash:

```
[error] GenServer #PID<0.1465.0> terminating
** (ArithmeticError) bad argument in arithmetic expression
    (sparkline_svg 0.3.0) lib/sparkline_svg/core.ex:132: SparklineSvg.Core.resize_x/3
    (sparkline_svg 0.3.0) lib/sparkline_svg/core.ex:62: anonymous fn/4 in SparklineSvg.Core.resize_datapoints/4
    (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (sparkline_svg 0.3.0) lib/sparkline_svg/core.ex:35: SparklineSvg.Core.compute/1
    (sparkline_svg 0.3.0) lib/sparkline_svg.ex:688: SparklineSvg.compute/1
    (sparkline_svg 0.3.0) lib/sparkline_svg.ex:605: SparklineSvg.to_svg/1
    (sparkline_svg 0.3.0) lib/sparkline_svg.ex:635: SparklineSvg.to_svg!/1
```

Maybe this could be handled by the library and return a better error?

If there are 0 values, I just don't show the sparkline, but I have a case where I can have 1 value:

In my stats I have a date selector that can display the last 7, 30 or 365 days, but the user can also choose to show a single day. In this case the library will crash, so a workaround might be showing 2 points when we have only 1, by repeating it:

<img width="387" alt="Captura de pantalla 2024-02-29 a las 8 54 53" src="https://github.com/abdelaz3r/sparkline_svg/assets/2629/8097201d-5163-476c-a86a-9b3499fcd947">

However this feels a bit weird, it might be preferable to just show a single dot and no line?

**Comment by abdelaz3r** [comment]
Thanks for creating the issue and providing clear explanations.

I've successfully reproduced the bug and added a test to address it.

On the display side, the case is already handled. It will now show only one central dot (if `show_dots/2` has been called) and a single centered horizontal line that does not take the full width (if `show_line/2` has been called).

I'll make a patch release to fix that.

**Comment by abdelaz3r** [comment]
And there is the fix!

Btw, you don't have to handle an empty chart by yourself. With an empty datapoints the chart will be an empty SVG document (but with correct `width` and `height`). If you set the `:placeholder` option, it will show the placeholder centered.

**Comment by jaimeiniesta** [comment]
Thanks, that was fast!

I just tried the PR and it works great, here's how it appears when only one point is passed:

![Captura de pantalla 2024-02-29 a las 11 54 35](https://github.com/abdelaz3r/sparkline_svg/assets/2629/fa7fca3c-1d4b-4fd2-be40-56ae31478e20)

Also, thanks for the `:placeholder` option!
